# Generated by Django 3.0.3 on 2020-03-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200312_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='blog_images'),
            preserve_default=False,
        ),
    ]
