# Generated by Django 3.0.3 on 2020-03-13 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(height_field='height_field', upload_to='blog_images', width_field='width_field'),
        ),
    ]
